import { expect, test } from "@playwright/test";

test("landing showcase fits phones and starts onboarding without media or generation requests", async ({ page }) => {
  const errors: string[] = [];
  page.on("pageerror", (error) => errors.push(error.message));
  await page.route("**/api/**", (route) => route.fulfill({ status: 404, json: { error: "No live APIs in this test" } }));
  await page.route("**/api/billing/status", (route) => route.fulfill({ json: { tier: "free", enforced: false, studioAccess: true, checkedAt: new Date().toISOString() } }));
  await page.emulateMedia({ reducedMotion: "reduce" });
  await page.goto("/");
  await expect(page.getByRole("heading", { name: /You built the app/ })).toBeVisible();
  await expect(page.getByTestId("landing-video-placeholder")).toHaveCount(1);
  await expect(page.getByTestId("landing-video-placeholder").getByText("Your app deserves its main character moment", { exact: true })).toBeVisible();
  await expect(page.getByText("Your app deserves its main character moment", { exact: true })).toHaveCount(1);
  await expect(page.locator("video")).toHaveCount(0);
  await expect(page.getByRole("img", { name: "HypeJuice", exact: true })).toBeVisible();
  await expect(page.getByText("YOUR GROWTH AGENT", { exact: true })).toHaveCount(0);
  await expect(page.getByText("You keep shipping. Your agent makes the noise.", { exact: true })).toHaveCount(0);
  await expect(page.getByText(/HypeJuice learns your app inside out/)).toBeVisible();
  await expect(page.getByText(/HypeJuice learns your app inside out/)).toHaveCSS("font-size", "18px");
  await expect(page.getByRole("heading", { name: "100+ New Ideas from your AI Growth Agent in seconds", exact: true })).toBeVisible();
  await expect(page.getByText("New Ideas from your AI Growth Agent", { exact: true })).toBeVisible();
  await expect(page.getByText(/Choose your angle in seconds/)).toHaveCount(0);
  const cta = page.getByRole("button", { name: "Get Started", exact: true });
  await expect(cta).toBeEnabled();
  await expect(cta).toBeInViewport();
  await expect(page.getByTestId("landing-idea-count")).toHaveText("100+");
  await page.screenshot({ path: "/tmp/hypejuice-welcome.png" });
  await page.setViewportSize({ width: 320, height: 568 });
  await expect(cta).toBeInViewport();
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(320);
  await page.screenshot({ path: "/tmp/hypejuice-welcome-small.png" });
  await page.emulateMedia({ reducedMotion: "no-preference" });
  const count = page.getByTestId("landing-idea-count");
  await expect(count).toHaveText("10+");
  const label = page.getByText("New Ideas from your AI Growth Agent", { exact: true });
  const labelLeft = (await label.boundingBox())!.x;
  await expect(count).toHaveText("50+");
  await expect(count).toHaveText("100+");
  await expect(count).toHaveText("10+");
  expect((await label.boundingBox())!.x).toBeCloseTo(labelLeft, 0);
  await page.emulateMedia({ reducedMotion: "reduce" });
  await expect(count).toHaveText("100+");
  await cta.click();
  await expect(page.getByRole("button", { name: "Analyze with Growth Agent", exact: true })).toBeVisible();
  expect(errors).toEqual([]);
});
